##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
pipeline:
  - docker
  - helm
  - zip
zipGlobs:
  - node_modules/**
  - ./**
  - .env
staticAnalysis: true
excludeGlobs:
  - Dockerfile
  - .helmignore
  - .dockerignore
  - .git*
  - .git/
  - OWNER*
  - README.md
  - jenkins*
  - target/
  - charts/
  - cloudopsworks-ci
  - skafold*
  - gulpfile*
# cd:
#   env: staging
#   preview:
#     enabled: true
#     kubernetes: true
#     domain: example.com