##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
pipeline:
  - docker
  - helm
  - zip
zipGlobs:
  - node_modules/**
  - ./**
  - .env
excludeGlobs:
  - Dockerfile
  - .helmignore
  - .dockerignore
  - .git*
  - .git/
  - OWNER*
  - README.md
  - jenkins*
  - target/
  - charts/
  - cloudopsworks-ci
  - skafold*
  - gulpfile*
# cd:
#   env: staging