#annotations: []
#podAnnotations: []
#replicaCount: 1
#env: []
probe:
  path: /healthz
#  port: 8082
startupProbe:
  enabled: true
#livenessProbe:
#readinessProbe:
ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: UAT-URL
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: PROJECT_NAME-helm
                port:
                  number: 80

#env:
# Uncomment below to disable the aws-sdk instrumentation if not disabled in the code for health checks
#  - name: OTEL_NODE_DISABLED_INSTRUMENTATIONS
#    value: "aws-sdk"

# Uncomment to enable opentelemetry instrumentation
#podAnnotations:
#  instrumentation.opentelemetry.io/inject-nodejs: "true"
