---
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}-portal-environment
{{- else }}
  name: {{ template "fullname" . }}-portal-environment
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  .env: {{ .Values.config.dotenv | b64enc | quote }}