{{- if and (.Values.ingress.enabled) (not .Values.knativeDeploy) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
spec:
  rules:
{{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
{{- else }}
  {{- if .Values.service.name }}
  - host: {{ .Values.service.name }}
  {{- else }}
  - host: {{ template "fullname" . }}
  {{- end }}
{{- end }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
        {{- if .Values.service.name }}
            name: {{ .Values.service.name }}
        {{- else }}
            name: {{ template "fullname" . }}
        {{- end }}
            port: 
              number: 80
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
{{- if .Values.ingress.host }}
    - {{ .Values.ingress.host }}
{{- else }}
  {{- if .Values.service.name }}
    - {{ .Values.service.name }}
  {{- else }}
    - {{ template "fullname" . }}
  {{- end }}
{{- end }}
{{- if .Values.ingress.tls.secretName }}
    secretName: "{{ .Values.ingress.tls.secretName }}"
{{- else }}
  {{- if .Values.jxRequirements.ingress.domain }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
  {{- else }}
    secretName: "tls-{{ template "fullname" . }}-s"
  {{- end }}
{{- end }}
{{- end }}
  ingressClassName: {{ .Values.ingress.ingressClass }}
{{- end }}
