##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Release Build
on:
  # Run on create - but only on the support and release branches
  create:
  # Run only on branches PUSH except when charts are modified
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+**'
    branches:
      - develop
      - support/**
      - release/**
    paths-ignore:
      - '.github/**'
      - '!.github/vars/**'
      - '!.github/values/**'
  workflow_dispatch:

concurrency: build-${{ github.repository }}-${{ github.ref }}

# Permission Settings for the entire RUN
permissions:
  actions: write
  contents: write
  issues: write
  packages: write
  statuses: write

jobs:
  data:
    uses: {{REPO_OWNER}}/base-app-template/.github/workflows/cd-data.yml@v5
    if: |
      github.event_name == 'create' && 
      (startsWith(github.ref, 'refs/heads/support/') || startsWith(github.ref, 'refs/heads/release/')) ||
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    secrets:
      token: ${{ secrets.BOT_TOKEN_SCOPED }}

  build:
    needs:
      - data
    uses: ./.github/workflows/code-build.yml
    if: |
      github.event_name == 'create' && 
      (startsWith(github.ref, 'refs/heads/support/') || startsWith(github.ref, 'refs/heads/release/')) ||
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    with:
      buildEnvironment: ${{ needs.data.outputs.deploymentName }}
      isContainerized: ${{ needs.data.outputs.cloud_type == 'eks' || needs.data.outputs.cloud_type == 'aks' || needs.data.outputs.cloud_type == 'gke' || needs.data.outputs.cloud_type == 'kubernetes' }}
      environment: ${{ needs.data.outputs.environment }}
      targetName: ${{ needs.data.outputs.targetName }}
      isRelease: ${{ needs.data.outputs.isRelease == 'true' }}
      DOCKER_REGISTRY_ADDRESS: ${{ needs.data.outputs.dockerRegistry != '' && needs.data.outputs.dockerRegistry || vars.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ needs.data.outputs.helmRegistry != '' && needs.data.outputs.helmRegistry || vars.HELM_REGISTRY_ADDRESS }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      TARGET_CLOUD: ${{ needs.data.outputs.cloud }}
      AWS_REGION: ${{ needs.data.outputs.awsRegion != '' && needs.data.outputs.awsRegion || vars.BUILD_AWS_REGION }}
      AWS_STS_ROLE_ARN: ${{ needs.data.outputs.awsStsRoleArn != '' && needs.data.outputs.awsStsRoleArn || vars.BUILD_AWS_STS_ROLE_ARN }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  release:
    needs:
      - data
      - build
    uses: {{REPO_OWNER}}/base-app-template/.github/workflows/create-release.yml@v5
    if: ${{ startsWith(github.ref,'refs/tags/') }}
    with:
      ref_name: ${{ needs.build.outputs.semver }}
      release-tag: ${{ needs.build.outputs.semver }}
      pre-release: ${{ needs.data.outputs.isPreRelease == 'true' }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  clean-old-packages:
    needs:
      - data
      - build
      - release
    uses: {{REPO_OWNER}}/base-app-template/.github/workflows/clean-old-packages.yml@v5
    if: ${{ needs.data.outputs.hasQualifier != 'true' && needs.data.outputs.isLibrary == 'true'}}
    with:
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: npm
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  snyk-analysis:
    needs:
      - data
      - build
    if: ${{ needs.build.outputs.pipeline_snyk == 'true' && needs.data.outputs.hasQualifier != 'true' }}
    uses: ./.github/workflows/snyk-analysis.yml
    with:
      ref: ${{ github.head_ref }}
      semver: ${{ needs.build.outputs.semver }}
      snyk_url: ${{ vars.SNYK_URL }}
      source_artifacts: ${{ needs.build.outputs.source_artifacts_name }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      snyk_token: ${{ secrets.SNYK_TOKEN }}

  semgrep-analysis:
    needs:
      - data
      - build
    if: ${{ needs.build.outputs.pipeline_semgrep == 'true' && needs.data.outputs.hasQualifier != 'true' }}
    uses: ./.github/workflows/semgrep-analysis.yml
    with:
      ref: ${{ github.head_ref }}
      semver: ${{ needs.build.outputs.semver }}
      semgrep_url: ${{ vars.SEMGREP_URL }}
      source_artifacts: ${{ needs.build.outputs.source_artifacts_name }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      semgrep_token: ${{ secrets.SEMGREP_TOKEN }}

  sonar-analysis:
    needs:
      - data
      - build
    if: ${{ needs.build.outputs.pipeline_sonarqube == 'true' && needs.data.outputs.hasQualifier != 'true' }}
    uses: ./.github/workflows/sonar-analysis.yml
    with:
      ref: ${{ github.head_ref }}
      semver: ${{ needs.build.outputs.semver }}
      sonarqubeUrl: ${{ vars.SONARQUBE_URL }}
      source_artifacts: ${{ needs.build.outputs.source_artifacts_name }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      sonarqubeToken: ${{ secrets.SONARQUBE_TOKEN }}

  apis-sonar-analysis:
    needs:
      - data
      - build
      - sonar-analysis
    if: ${{ needs.build.outputs.pipeline_sonarqube == 'true' && needs.data.outputs.hasQualifier != 'true' && needs.data.outputs.apisEnabled == 'true' }}
    uses: ./.github/workflows/static-analysis-apis.yml
    with:
      ref: ${{ github.head_ref }}
      semver: ${{ needs.build.outputs.semver }}
      sonarqubeUrl: ${{ vars.SONARQUBE_URL }}
      source_artifacts: ${{ needs.build.outputs.source_artifacts_name }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      sonarqubeToken: ${{ secrets.SONARQUBE_TOKEN }}

  dependency-track:
    needs:
      - data
      - build
    if: ${{ needs.build.outputs.pipeline_dtrack == 'true' && needs.data.outputs.hasQualifier != 'true' }}
    uses: ./.github/workflows/dependency-track.yml
    with:
      projectName: ${{ needs.new_version.outputs.project_name }}
      projectType: ${{ needs.build.outputs.pipeline_dtrack_project_type }}
      semver: ${{ needs.build.outputs.semver }}
      dependencyTrackUrl: ${{ vars.DEPENDENCYTRACK_URL }}
      source_artifacts: ${{ needs.build.outputs.source_artifacts_name }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      dependencyTrackToken: ${{ secrets.DEPENDENCYTRACK_TOKEN }}

  deploy-release:
    needs:
      - data
      - build
      - release
    uses: {{REPO_OWNER}}/base-app-template/.github/workflows/deploy.yml@v5
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.isLibrary != 'true' }}
    with:
      is_release: true
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
      target_cloud: ${{ needs.data.outputs.cloud }}
      target_cloud_type: ${{ needs.data.outputs.cloudType }}
      apis_enabled: ${{ needs.data.outputs.apisEnabled == 'true' }}
      runner_set: ${{ needs.data.outputs.runnerSet != '' && needs.data.outputs.runnerSet || vars.DEPLOYMENT_RUNNER_SET }}
      DOCKER_REGISTRY_ADDRESS: ${{ needs.data.outputs.dockerRegistry != '' && needs.data.outputs.dockerRegistry || vars.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ needs.data.outputs.helmRegistry != '' && needs.data.outputs.helmRegistry || vars.HELM_REGISTRY_ADDRESS }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ needs.data.outputs.awsRegion != '' && needs.data.outputs.awsRegion || vars.DEPLOYMENT_AWS_REGION }}
      STS_ROLE_ARN: ${{ needs.data.outputs.awsStsRoleArn != '' && needs.data.outputs.awsStsRoleArn || vars.DEPLOYMENT_AWS_STS_ROLE_ARN }}
      AZURE_RG: ${{ needs.data.outputs.azureResourceGroup != '' && needs.data.outputs.azureResourceGroup || vars.DEPLOYMENT_AZURE_RG }}
      download_artifacts: ${{ needs.build.outputs.artifacts_name }}
      source_artifacts: ${{ needs.build.outputs.source_artifacts_name }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  deploy-prerelease:
    needs:
      - data
      - build
    uses: {{REPO_OWNER}}/base-app-template/.github/workflows/deploy.yml@v5
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.isLibrary != 'true' && ( startsWith(github.ref,'refs/heads/release/') || startsWith(github.ref,'refs/heads/develop') || startsWith(github.ref,'refs/heads/support/') ) }}
    with:
      is_release: false
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: MAVEN
      deployment_name: ${{ needs.data.outputs.deploymentName }}
      target_cloud: ${{ needs.data.outputs.cloud }}
      target_cloud_type: ${{ needs.data.outputs.cloudType }}
      apis_enabled: ${{ needs.data.outputs.apisEnabled == 'true' }}
      runner_set: ${{ needs.data.outputs.runnerSet != '' && needs.data.outputs.runnerSet || vars.DEPLOYMENT_RUNNER_SET }}
      DOCKER_REGISTRY_ADDRESS: ${{ needs.data.outputs.dockerRegistry != '' && needs.data.outputs.dockerRegistry || vars.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ needs.data.outputs.helmRegistry != '' && needs.data.outputs.helmRegistry || vars.HELM_REGISTRY_ADDRESS }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ needs.data.outputs.awsRegion != '' && needs.data.outputs.awsRegion || vars.DEPLOYMENT_AWS_REGION }}
      STS_ROLE_ARN: ${{ needs.data.outputs.awsStsRoleArn != '' && needs.data.outputs.awsStsRoleArn || vars.DEPLOYMENT_AWS_STS_ROLE_ARN }}
      AZURE_RG: ${{ needs.data.outputs.azureResourceGroup != '' && needs.data.outputs.azureResourceGroup || vars.DEPLOYMENT_AZURE_RG }}
      download_artifacts: ${{ needs.build.outputs.artifacts_name }}
      source_artifacts: ${{ needs.build.outputs.source_artifacts_name }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  # Deploy after build APIs
  deploy-apis:
    needs:
      - data
      - build
    uses: {{REPO_OWNER}}/base-app-template/.github/workflows/deploy-apis.yml@v5
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.apisEnabled == 'true' && needs.data.outputs.hasQualifier != 'true'  && needs.data.outputs.isLibrary != 'true' }}
    with:
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
      target_cloud: ${{ needs.data.outputs.cloud }}
      apis_enabled: ${{ needs.data.outputs.apisEnabled == 'true' }}
      runner_set: ${{ needs.data.outputs.runnerSet != '' && needs.data.outputs.runnerSet || vars.DEPLOYMENT_RUNNER_SET }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ needs.data.outputs.awsRegion != '' && needs.data.outputs.awsRegion || vars.DEPLOYMENT_AWS_REGION }}
      STS_ROLE_ARN: ${{ needs.data.outputs.awsStsRoleArn != '' && needs.data.outputs.awsStsRoleArn || vars.DEPLOYMENT_AWS_STS_ROLE_ARN }}
      AZURE_RG: ${{ needs.data.outputs.azureResourceGroup != '' && needs.data.outputs.azureResourceGroup || vars.DEPLOYMENT_AZURE_RG }}
      download_artifacts: ${{ needs.build.outputs.artifacts_name }}
      source_artifacts: ${{ needs.build.outputs.source_artifacts_name }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  # Deploy after build APIs
  deploy-apis-only:
    needs:
      - data
      - build
    uses: {{REPO_OWNER}}/base-app-template/.github/workflows/deploy-apis.yml@v5
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.apisEnabled == 'true' && needs.data.outputs.hasQualifier == 'true' && needs.data.outputs.isLibrary != 'true' }}
    with:
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
      target_cloud: ${{ needs.data.outputs.cloud }}
      apis_enabled: ${{ needs.data.outputs.apisEnabled == 'true' }}
      runner_set: ${{ needs.data.outputs.runnerSet != '' && needs.data.outputs.runnerSet || vars.DEPLOYMENT_RUNNER_SET }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ needs.data.outputs.awsRegion != '' && needs.data.outputs.awsRegion || vars.DEPLOYMENT_AWS_REGION }}
      STS_ROLE_ARN: ${{ needs.data.outputs.awsStsRoleArn != '' && needs.data.outputs.awsStsRoleArn || vars.DEPLOYMENT_AWS_STS_ROLE_ARN }}
      AZURE_RG: ${{ needs.data.outputs.azureResourceGroup != '' && needs.data.outputs.azureResourceGroup || vars.DEPLOYMENT_AZURE_RG }}
      download_artifacts: ${{ needs.build.outputs.artifacts_name }}
      source_artifacts: ${{ needs.build.outputs.source_artifacts_name }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}
