##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Check on Pull request
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited

permissions:
  contents: read
  packages: write
  statuses: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  plan:
    uses: {{REPO_OWNER}}/base-app-template/.github/workflows/on-pull-request.yml@v4
    secrets:
      token: ${{ secrets.BOT_TOKEN }}