##
# (c) 2023 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Do Retry command
on:
  repository_dispatch:
    types:
      - retry-command

permissions:
  issues: write
  checks: read
  deployments: write
  contents: read
  packages: read
  statuses: write

jobs:
  promote:
    uses: ${{ github.repository_owner }}/base-app-template/.github/workflows/slash-on-retry-automerge.yml@v3
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
