##
# (c) 2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Static Analysis Process - SonarQube
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      semver:
        required: false
        type: string
      sonarqubeUrl:
        required: true
        type: string
      source_artifacts:
        required: true
        type: string

    secrets:
      token:
        required: true
      sonarqubeToken:
        required: true

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      # Proceed with checkout of source with all the references (depth=0)  
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.token }}
          ref: ${{ inputs.ref }}
      # Get pipeline conf node version
      - name: Get pipeline node version
        id: node_version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.node.version // "20"' ./.github/vars/inputs-global.yaml
      # Get pipeline conf node dist
      - name: Get pipeline node dist
        id: node_dist
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.node.dist // "adopt"' ./.github/vars/inputs-global.yaml
      # Setup Node JS for builds with version provided
      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.node_version.outputs.result }}"
          check-latest: true
          token: ${{ secrets.token }}
      # Cache all NPM packages
      - name: Cache NPM packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Get project name with yq in the process strip starting @ if exists and change any / to _
      - name: Get project name
        id: project_name
        uses: mikefarah/yq@master
        with:
          cmd: yq e -oy '.name | sub("^@","") | sub("/","_")' ./package.json

      # Get project description
      - name: Get project description
        id: project_description
        uses: mikefarah/yq@master
        with:
          cmd: yq e -oy '.description' ./package.json

      # Get project type
      - name: Get project type
        id: project_type
        uses: mikefarah/yq@master
        with:
          cmd: yq e -oy '.type' ./package.json

      # Run versioning to tag the source
      - name: Run Versioning setup
        run: make version

      # Test the code!
      - name: Static Test Code
        env:
          SONAR_HOST_URL: ${{ inputs.sonarqubeUrl }}
          SONAR_TOKEN: ${{ secrets.sonarqubeToken }}
        run: |
          npm install
          CI=true DISPLAY=:99 npm test --if-present

      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.sonarqubeToken }}
          SONAR_HOST_URL: ${{ inputs.sonarqubeUrl }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ steps.project_name.outputs.result }}
            -Dsonar.projectVersion=${{ inputs.semver }}
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.language=javascript
            -Dsonar.exclusions=node_modules/**,coverage/**,test/**,tests/**,charts/**,tronador/**,dist/**,build/**
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js
            -Dsonar.test.exclusions=node_modules/**,coverage/**,test/**,tests/**
#            -Dsonar.branch.name=${{ github.ref }}
