organization_name: "ORG_NAME"
organization_unit: "ORG_UNIT"
environment_name: "ENV_NAME"
repository_owner: "REPO_OWNER" # Required
frontend: true | false # Set frontend=true to deploy only /build directory into ngnix enabled Dockerfile
#docker_inline: |
#  # Dockerfile content here
#  # Example:
#  # WORKDIR /app
#  # COPY package*.json ./
#  # COPY ./mydir ./my dest
#docker_args: |
#  ARG1=value1
#  ARG2=value2
#  ARG3=value3
#custom_run_command: node run start
#api_files_dir: "relative-path-to-apidefs"
# Optional Additional ENV variables
#node_extra_env: |
#  ENV_VAR1=value1
#  ENV_VAR2=value2
#custom_install_command: npm install
#custom_build_command: npm run build
#node_build_dir: ./build