organization_name: "ORG_NAME"
environment_name: "ENV_NAME|APP_NAME"
namespace: "GITHUB TEAM OWNER|Beanstalk|Automation|Lambda"
repository_owner: "REPO_OWNER"
#api_files_dir: "relative-path-to-apidefs"
# Required ENV variables
#node_extra_env: |
#  ENV_VAR1=value1
#  ENV_VAR2=value2
#custom_install_command: npm install
#custom_build_command: npm run build