organization_name: "ORG_NAME"
organization_unit: "ORG_UNIT"
environment_name: "ENV_NAME"
repository_owner: "REPO_OWNER" # Required
frontend: true | false # Set frontend=true to deploy only /build directory into ngnix enabled Dockerfile
#docker_inline: |
#  # Dockerfile content here
#  # Example:
#  # FROM node:14
#  # WORKDIR /app
#  # COPY package*.json ./
#  # RUN npm install
#  # COPY . .
#  # EXPOSE 8080
#  # CMD ["node", "server.js"]
#api_files_dir: "relative-path-to-apidefs"
# Optional Additional ENV variables
#node_extra_env: |
#  ENV_VAR1=value1
#  ENV_VAR2=value2
#custom_install_command: npm install
#custom_build_command: npm run build
#node_build_dir: ./build