organization_name: "ORG_NAME"
environment_name: "ENV_NAME|APP_NAME"
namespace: "GITHUB TEAM OWNER|Beanstalk|Automation|Lambda"
repository_owner: "REPO_OWNER"
#api_files_dir: "relative-path-to-apidefs"
#node_build_required_files: # Required files for node build, relative to environment values ROOT
#  - config1.json
#  - config2.json