##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
name: Create Release
on:
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string

    secrets:
      BOT_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: all-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          body_path: CHANGELOG.md
          name: "Release v${{ inputs.release-tag }}"
          tag_name: v${{ inputs.release-tag }}
          files: |
            target/*.zip
            target/*.jar
          