##
# (c) 2022 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Dependency Track Analysis
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

    secrets:
      BOT_TOKEN:
        required: true
      dependencyTrackUrl:
        required: true
      dependencyTrackToken:
        required: true

jobs:
  dependency-track:
    runs-on: ubuntu-latest
    steps:
      # Proceed with checkout of source with all the references (depth=0)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ inputs.ref }}
      # Get pipeline conf node version
      - name: Get pipeline node version
        id: node_version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.build.node.version // "14"' ./cloudopsworks-ci.yaml
      # Get pipeline conf node dist
      - name: Get pipeline node dist
        id: node_dist
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.build.node.dist // "adopt"' ./cloudopsworks-ci.yaml
      # Setup Node JS for builds with version provided
      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.node_version.outputs.result }}"
          distribution: "${{ steps.node_dist.outputs.result }}"
      # Cache all NPM packages
      - name: Cache NPM packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # SBOM generation
      - name: SBOM Generation for Dtrack
        uses: AppThreat/cdxgen-action@v1
        with:
          output: "./reports/bom.xml"
          serverUrl: ${{ secrets.dependencyTrackUrl }}
          apiKey: ${{ secrets.dependencyTrackToken }}

      # SBOM generated reports upload
      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
