##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: NodeJS Hotfix Build
on:
  # Run only on branches PUSH except when charts are modified
  pull_request:
    branches:
      - hotfix-*
    types:
      - closed
  workflow_dispatch:

# Permission Settings for the entire RUN
permissions:
  actions: write
  contents: write
  issues: write
  packages: write
  statuses: write

jobs:
  check_hotfix:
    runs-on: ubuntu-latest
    outputs:
      hotfix_version: ${{ steps.version.outputs.ver }}
    steps:
      - name: Version Extract
        id: version
        run: |
          echo "ver=$(echo ${{ github.ref }} | sed -En 's/.*(-|v)?([0-9]+\.[0-9]+\.[0-9]+\-.+)$/\2/p')" >> $GITHUB_OUTPUT

  new_version:
    needs:
      - check_hotfix
    uses: cloudopsworks/node-app-template/.github/workflows/code-tag.yml@v1
    with:
      DOCKER_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      isAuto: false
      tagRelease: ${{ needs.check_hotfix.outputs.hotfix_version }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

  build:
    needs:
      - new_version
    uses: cloudopsworks/node-app-template/.github/workflows/code-build.yml@v1
    with:
      isHotfix: true
      semver: ${{ needs.new_version.outputs.release_version }}
      ref: ${{ needs.new_version.outputs.release_tag }}
      DOCKER_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      TARGET_CLOUD: ${{ vars.TARGET_CLOUD }}
      AWS_REGION: ${{ vars.BUILD_AWS_REGION }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  release:
    needs:
      - build
      - new_version
    uses: cloudopsworks/base-app-template/.github/workflows/create-release.yml@v1
    with:
      release-tag: ${{ needs.new_version.outputs.release_version }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  static-analysis:
    needs:
      - build
      - new_version
    if: ${{ needs.build.outputs.pipeline_sonarqube == 'true' }}
    uses: cloudopsworks/node-app-template/.github/workflows/static-analysis.yml@v1
    with:
      ref: ${{ needs.new_version.outputs.release_tag }}
      sonarqubeUrl: ${{ vars.SONARQUBE_URL }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      sonarqubeToken: ${{ secrets.SONARQUBE_TOKEN }}

  dependency-track:
    needs:
      - build
      - new_version
    if: ${{ needs.build.outputs.pipeline_dtrack == 'true' }}
    uses: cloudopsworks/node-app-template/.github/workflows/dependency-track.yml@v1
    with:
      projectName: ${{ needs.new_version.outputs.project_name }}
      projectType: ${{ needs.build.outputs.pipeline_dtrack_project_type }}
      ref: ${{ needs.new_version.outputs.release_tag }}
      dependencyTrackUrl: ${{ vars.DEPENDENCYTRACK_URL }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      dependencyTrackToken: ${{ secrets.DEPENDENCYTRACK_TOKEN }}

