
##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: NodeJS Build
on:
  # Run only on branches PUSH except when charts are modified
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:
    
# Permission Settings for the entire RUN
permissions:
  actions: write
  contents: write
  issues: write
  packages: write
  statuses: write

jobs:
  new_version:
    uses: cloudopsworks/node-app-template/.github/workflows/code-tag.yml@master
    secrets:
      DOCKER_REGISTRY_ADDRESS: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}
      BOT_USER: ${{ secrets.BOT_USER }}
      BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

  build:
    needs:
      - new_version
    uses: cloudopsworks/node-app-template/.github/workflows/code-build.yml@master
    with:
      semver: ${{ needs.new_version.outputs.release_version }} 
      ref: ${{ needs.new_version.outputs.release_tag }}
    secrets:
      DOCKER_REGISTRY_ADDRESS: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}
      BOT_USER: ${{ secrets.BOT_USER }}
      BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      TARGET_CLOUD: ${{ secrets.TARGET_CLOUD }}
      AWS_REGION: ${{ secrets.BUILD_AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  release:
    needs:
      - build
      - new_version
    uses: cloudopsworks/base-app-template/.github/workflows/create-release.yml@master
    with:
      release-tag: ${{ needs.new_version.outputs.release_version }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  static-analysis:
    needs:
      - build
      - new_version
    if: needs.build.outputs.pipeline_sonarqube
    uses: cloudopsworks/node-app-template/.github/workflows/static-analysis.yml@master
    with:
      ref: ${{ needs.new_version.outputs.release_tag }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      sonarqubeUrl: ${{ secrets.SONARQUBE_URL }}
      sonarqubeToken: ${{ secrets.SONARQUBE_TOKEN }}

  dependency-track:
    needs:
      - build
      - new_version
    if: needs.build.outputs.pipeline_dtrack
    uses: cloudopsworks/node-app-template/.github/workflows/dependency-track.yml@master
    with:
      ref: ${{ needs.new_version.outputs.release_tag }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      dependencyTrackUrl: ${{ secrets.DEPENDENCYTRACK_URL }}
      dependencyTrackToken: ${{ secrets.DEPENDENCYTRACK_TOKEN }}

  delivery:
    needs:
      - build
      - release
      - new_version
    uses: cloudopsworks/base-app-template/.github/workflows/delivery-push.yml@master
    with:
      release_version: ${{ needs.new_version.outputs.release_version }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

