##
# (c) 2023 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Release Build
on:
  # Run only on branches PUSH except when charts are modified
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+**'
    branches:
      - develop
      - support/**
      - release/**
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

concurrency: build-${{ github.repository }}-${{ github.ref }}

# Permission Settings for the entire RUN
permissions:
  actions: write
  contents: write
  issues: write
  packages: write
  statuses: write

jobs:
  data:
    uses: cloudopsworks/base-app-template/.github/workflows/cd-data.yml@v3
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  build:
    needs:
      - data
    uses: ./.github/workflows/code-build.yml
    if: ${{ needs.data.outputs.hasQualifier != 'true' }}
    with:
      isRelease: true
      TARGET_CLOUD: ${{ needs.data.outputs.cloud }}
      DOCKER_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ vars.BUILD_AWS_REGION }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  release:
    needs:
      - data
      - build
    uses: cloudopsworks/base-app-template/.github/workflows/create-release.yml@v3
    if: ${{ needs.data.outputs.hasQualifier != 'true' && startsWith(github.ref,'refs/tags/') }}
    with:
      ref_name: v${{ needs.build.outputs.semver }}
      release-tag: v${{ needs.build.outputs.semver }}
      pre-release: ${{ needs.data.outputs.isPreRelease == 'true' }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  clean-old-packages:
    needs:
      - data
      - build
      - release
    uses: cloudopsworks/base-app-template/.github/workflows/clean-old-packages.yml@v3
    if: ${{ needs.data.outputs.hasQualifier != 'true' }}
    with:
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: npm
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  static-analysis:
    needs:
      - data
      - build
    if: ${{ needs.build.outputs.pipeline_sonarqube == 'true' && needs.data.outputs.hasQualifier != 'true' }}
    uses: ./.github/workflows/static-analysis.yml
    with:
      ref: ${{ github.head_ref }}
      semver: ${{ needs.build.outputs.semver }}
      sonarqubeUrl: ${{ vars.SONARQUBE_URL }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      sonarqubeToken: ${{ secrets.SONARQUBE_TOKEN }}

  apis-static-analysis:
    needs:
      - data
      - build
      - static-analysis
    if: ${{ needs.build.outputs.pipeline_sonarqube == 'true' && needs.data.outputs.hasQualifier != 'true' && needs.data.outputs.apisEnabled == 'true' }}
    uses: ./.github/workflows/static-analysis-apis.yml
    with:
      ref: ${{ github.head_ref }}
      semver: ${{ needs.build.outputs.semver }}
      sonarqubeUrl: ${{ vars.SONARQUBE_URL }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      sonarqubeToken: ${{ secrets.SONARQUBE_TOKEN }}

  dependency-track:
    needs:
      - data
      - build
    if: ${{ needs.build.outputs.pipeline_dtrack == 'true' && needs.data.outputs.hasQualifier != 'true' }}
    uses: ./.github/workflows/dependency-track.yml
    with:
      projectName: ${{ needs.new_version.outputs.project_name }}
      projectType: ${{ needs.build.outputs.pipeline_dtrack_project_type }}
      semver: ${{ needs.build.outputs.semver }}
      dependencyTrackUrl: ${{ vars.DEPENDENCYTRACK_URL }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      dependencyTrackToken: ${{ secrets.DEPENDENCYTRACK_TOKEN }}

  # Deployment with upgraded process
  deployment-process:
    needs:
      - data
    if: ${{ needs.data.outputs.deliveryPush != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: 'echo "Deploy to environment: ${{ needs.data.outputs.environment }}"'

  deploy-release:
    needs:
      - data
      - build
      - release
      - deployment-process
    uses: cloudopsworks/base-app-template/.github/workflows/deploy.yml@v3
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.hasQualifier != 'true' }}
    with:
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
      target_cloud: ${{ needs.data.outputs.cloud }}
      target_cloud_type: ${{ needs.data.outputs.cloudType }}
      apis_enabled: ${{ needs.data.outputs.apisEnabled == 'true' }}
      DOCKER_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ vars.DEPLOYMENT_AWS_REGION }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  deploy-prerelease:
    needs:
      - data
      - build
      - deployment-process
    uses: cloudopsworks/base-app-template/.github/workflows/deploy.yml@v3
    if: ${{ needs.data.outputs.isEnabled == 'true' && ( startsWith(github.ref,'refs/heads/release/') || startsWith(github.ref,'refs/heads/develop') || startsWith(github.ref,'refs/heads/support/') ) }}
    with:
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
      target_cloud: ${{ needs.data.outputs.cloud }}
      target_cloud_type: ${{ needs.data.outputs.cloudType }}
      apis_enabled: ${{ needs.data.outputs.apisEnabled == 'true' }}
      DOCKER_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ vars.DEPLOYMENT_AWS_REGION }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  # Deploy only on qualifier setting
  deploy-only:
    needs:
      - data
      - deployment-process
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.hasQualifier == 'true'  && needs.data.outputs.deliveryPush != 'true'  }}
    uses: ./.github/workflows/code-version.yml
    with:
      deployment_name: ${{ needs.data.outputs.deploymentName }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  deploy-version:
    needs:
      - data
      - deploy-only
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.hasQualifier == 'true' }}
    uses: cloudopsworks/base-app-template/.github/workflows/deploy.yml@v3
    with:
      release_version: ${{ needs.version-delivery.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.version-delivery.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
      target_cloud: ${{ needs.data.outputs.cloud }}
      target_cloud_type: ${{ needs.data.outputs.cloudType }}
      apis_enabled: ${{ needs.data.outputs.apisEnabled == 'true' }}
      DOCKER_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ vars.DOCKER_REGISTRY_ADDRESS }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ vars.DEPLOYMENT_AWS_REGION }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  # Legacy Delivery to Environment support
  delivery-to-env:
    needs:
      - data
    if: ${{ needs.data.outputs.deliveryPush == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: 'echo "Delivery to legacy environment: ${{ needs.data.outputs.environment }}"'

  version-delivery:
    needs:
      - data
      - delivery-to-env
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.hasQualifier == 'true'  }}
    uses: ./.github/workflows/code-version.yml
    with:
      deployment_name: ${{ needs.data.outputs.deploymentName }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  delivery-only:
    needs:
      - data
      - version-delivery
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.hasQualifier == 'true' }}
    uses: cloudopsworks/base-app-template/.github/workflows/delivery-push.yml@v3
    with:
      release_version: ${{ needs.version-delivery.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.version-delivery.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  delivery-release:
    needs:
      - data
      - build
      - release
      - delivery-to-env
    uses: cloudopsworks/base-app-template/.github/workflows/delivery-push.yml@v3
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.hasQualifier != 'true' }}
    with:
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  delivery-prerelease:
    needs:
      - data
      - build
      - delivery-to-env
    uses: cloudopsworks/base-app-template/.github/workflows/delivery-push.yml@v3
    if: ${{ needs.data.outputs.isEnabled == 'true' && ( startsWith(github.ref,'refs/heads/release/') || startsWith(github.ref,'refs/heads/develop') || startsWith(github.ref,'refs/heads/support/') ) }}
    with:
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  # Deploy after build APIs
  deploy-apis:
    needs:
      - data
      - build
      - deployment-process
    uses: cloudopsworks/base-app-template/.github/workflows/deploy-apis.yml@v3
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.apisEnabled == 'true' && needs.data.outputs.hasQualifier != 'true' }}
    with:
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
      target_cloud: ${{ needs.data.outputs.cloud }}
      apis_enabled: ${{ needs.data.outputs.apisEnabled == 'true' }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ vars.DEPLOYMENT_AWS_REGION }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}

  # Deploy after build APIs
  deploy-apis-only:
    needs:
      - data
      - delivery-to-env
    uses: cloudopsworks/base-app-template/.github/workflows/deploy-apis.yml@v3
    if: ${{ needs.data.outputs.isEnabled == 'true' && needs.data.outputs.apisEnabled == 'true' }}
    with:
      release_version: ${{ needs.build.outputs.semver }}
      release_name: ${{ needs.data.outputs.targetName }}
      environment: ${{ needs.data.outputs.environment }}
      package_name: ${{ needs.build.outputs.package_name }}
      package_type: NPM
      deployment_name: ${{ needs.data.outputs.deploymentName }}
      target_cloud: ${{ needs.data.outputs.cloud }}
      apis_enabled: ${{ needs.data.outputs.apisEnabled == 'true' }}
      BOT_USER: ${{ vars.BOT_USER }}
      BOT_EMAIL: ${{ vars.BOT_EMAIL }}
      AWS_REGION: ${{ vars.DEPLOYMENT_AWS_REGION }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_ID: ${{ secrets.AZURE_SERVICE_ID }}
      AZURE_SERVICE_SECRET: ${{ secrets.AZURE_SERVICE_SECRET }}
