
##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
name: NodeJS Build
on:
  # Run only on branches PUSH except when charts are modified
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:
    
# Permission Settings for the entire RUN
permissions:
  actions: write
  contents: write
  issues: write
  packages: write
  statuses: write

jobs:
  build:
    uses: cloudopsworks/node-app-template/.github/workflows/code-build.yml@master
    secrets:
      DOCKER_REGISTRY_ADDRESS: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}
      HELM_REGISTRY_ADDRESS: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}
      BOT_USER: ${{ secrets.BOT_USER }}
      BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      dockerRegistryUser: ${{ secrets.AZURE_SERVICE_ID }}
      dockerRegistryPassword: ${{ secrets.AZURE_SERVICE_SECRET }}
      helmRegistryUser: ${{ secrets.AZURE_SERVICE_ID }}
      helmRegistryPassword: ${{ secrets.AZURE_SERVICE_SECRET }}

  release:
    needs:
      - build
    uses: cloudopsworks/base-app-template/.github/workflows/create-release.yml@master
    with:
      release-tag: ${{ needs.build.outputs.release_version }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  static-analysis:
    needs:
      - build
    uses: cloudopsworks/node-app-template/.github/workflows/static-analysis.yml@master
    with:
      ref: v${{ needs.build.outputs.release_version }}
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      sonarqubeUrl: ${{ secrets.SONARQUBE_URL }}
      sonarqubeToken: ${{ secrets.SONARQUBE_TOKEN }}

  delivery:
    needs:
      - build
      - static-analysis
      - release
    uses: cloudopsworks/base-app-template/.github/workflows/delivery-push.yml@master
    with:
      release_version: ${{ needs.build.outputs.release_version }}
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

