##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
name: Chatops Agent
on:
  issue_comment:
    types:
      - created

permissions:
  issues: write
  contents: write
  packages: read
  pull-requests: write
  statuses: write
  security-events: write

jobs:
  gitops:
    uses: cloudopsworks/base-app-template/slash-commants.yml@master
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
