##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Chatops Agent
on:
  issue_comment:
    types:
      - created

permissions:
  issues: write
  contents: write
  packages: read
  pull-requests: write
  statuses: write
  security-events: write

jobs:
  gitops:
    uses: cloudopsworks/base-app-template/.github/workflows/slash-commands.yml@master
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
