##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
name: Do Promote command
on:
  repository_dispatch:
    types:
      - promote-command

permissions:
  issues: write
  checks: read
  deployments: write
  contents: read
  packages: read
  statuses: write

jobs:
  promote:
    uses: cloudopsworks/base-app-template/.github/workflows/slash-on-promote.yml@master
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
