##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
name: Slash command on Approve/LGTM
on:
  repository_dispatch:
    types:
      - approved-command
      - approve-command
      - lgtm-command
permissions:
  issues: write
  contents: write
  packages: read
  statuses: write
  pull-requests: write

jobs:
  approve:
    uses: cloudopsworks/base-app-template/slash-on-approve.yml@master
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
