##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
name: Static Analysis Process
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

    secrets:
      BOT_TOKEN:
        required: true
      sonarqubeUrl:
        required: true
      sonarqubeToken:
        required: true

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      # Proceed with checkout of source with all the references (depth=0)  
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ inputs.ref }}
      # Setup Node JS for builds
      - name: Set Node 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          distribution: "adopt"
      # Test the code!
      - name: Static Test Code
        env:
          SONARQUBE_URL: ${{ secrets.sonarqubeUrl }}
          SONARQUBE_TOKEN: ${{ secrets.sonarqubeToken }}
        run: |
          npm install -D gulp
          node ./node_modules/gulp/bin/gulp.js
